global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'receipt-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['receipt-service:8180']

  - job_name: 'validation-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['validation-service:8181']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8182']