server:
  port: 8180

spring:
  application:
    name: receipt-service
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5433/receipt_db
    username: receiptAdmin
    password: receiptAdmin
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,traces
  tracing:
    export:
      enabled: true
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces