server:
  port: 8180

spring:
  application:
    name: receipt-service
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5433/expense_platform_db}
    username: ${DB_USERNAME:devAdmin}
    password: ${DB_PASSWORD:devAdmin}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

app:
  kafka:
    topics:
      receipt-created: receipt-created

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}