server:
  port: 8180

spring:
  application:
    name: receipt-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/expense_platform_db
    username: devAdmin
    password: devAdmin
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  kafka:
    bootstrap-servers: localhost:9094
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

app:
  kafka:
    topics:
      receipt-created: receipt-created

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,traces
  tracing:
    export:
      enabled: true
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces