server:
  port: 8183

spring:
  application:
    name: ai-classification-service

  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5433/expense_platform_db}
    username: ${DB_USERNAME:devAdmin}
    password: ${DB_PASSWORD:devAdmin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:ai-classification-service-group}
      auto-offset-reset: earliest

app:
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      model: ${OLLAMA_MODEL:qwen2.5:1.5b}

  kafka:
    topics:
      receipt-created: receipt-created
      receipt-classified: receipt-classified

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}

logging:
  level:
    root: INFO
    com.jeronimo.ai_classification_service: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: WARN

resilience4j:
  circuitbreaker:
    instances:
      ollamaAi:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 2

  retry:
    instances:
      ollamaAi:
        maxAttempts: 2
        waitDuration: 1s

  timelimiter:
    instances:
      ollamaAi:
        timeoutDuration: 8s